### PR TITLE
Added Emoji Support :clap: :fire: :clap:

### PR DESCRIPTION
**Pull request by itsWill**
💥 Emojis are here! 💥  

I've added some tests to keep it 💯 

This is implemented using the ⚡  `gemoji` gem ⚡ 

I've also made all titles titleized but don't know if that is always appropriate ❓ ❔ ❓ 

☀️  emojineers at 🚜  ☀️

### CODE REVIEW

**Comment by sophiedeziel** [comment]
Thanks for the pull request! That the best PR description I've seen here!!! I'll review ASAP

**Comment by sophiedeziel** [comment]
Before I review, can you fix the failing tests?

**Comment by itsWill** [comment]
I'll have a look after the weekend but at a quick glance they seem quite unrelated.

**Comment by sophiedeziel** [comment]
Seems that VCR is not working for some reason.

**Comment by sophiedeziel** [comment]
Forget what I said, VCR is not installed on that branch. I'll see the env vars in travis

**Comment by sophiedeziel** [comment]
I found the issue. Circle-CI does not provide env vars to untrusted builds. Builds from forks are considered untrustworthy. Two solutions:
1. I have set up VCR in my other pull request that will solve that problem. There is a little extra work I have to do to make it work without env vars.. You can wait for it to be ready and merged and sync your branch to it.
2. You can cherry-pick those VCR commits and complete the work
3. I added you to the contributors of the projects. That means you can push your branch to that repository instead of your fork. You'll have to open a new pull-request.

I recommend solution 3. Easiest.

**Comment by itsWill** [comment]
closed because we opened new equivalent PR to fix failing tests

**Pull request closed without merging**
