### PR TITLE
Better factories with linting and traits

### PR DESCRIPTION
**Pull request by steakunderscore**
* Wrote the rest of the factories
+ Added test for factory lint
+ Added seeds to get developers started faster
* Fixed tests to use factory traits, rather than separate factories

### CODE REVIEW

**Comment by mathieugagne** [comment]
I'm good with this PR. :+1: 
Nice work with the factory traits.

@cawel do you second?

**Comment by mathieugagne** [comment]
Why would coveralls complain if coverage didn't decreased? I'm not a big user of coveralls. Anyone got an explanation?

**Comment by cawel** [comment]
@mathieugagne All those spec improvements look good to me. Nice work indeed :+1: 

As for seeding using FactoryGirl, [ThoughtBot actually discourages this practice](https://robots.thoughtbot.com/factory_girl-for-seed-data), but I remain unconvinced by their argument. And I have done that in the past several times (seeding using FactoryGirl) and so far I haven't been disappointed.

As for the coveralls, I'm also new to that tool. I can see [on the build report page](https://coveralls.io/builds/5163126) that the files in the "changed" list do not appear to have their coverage changed. Moreover, those "changed" files are specs, where coverage should be irrelevant. I'm clueless.

**Comment by mathieugagne** [comment]
FactoryGirl in seeds. :ok: 
Coveralls. :ok: :confused: Will pass.

**Pull request merged**
