### PR TITLE
[Chore] #120 - Responsive Navbar

### PR DESCRIPTION
**Pull request by mdeloupy**

### CODE REVIEW

**Comment by mdeloupy** [comment]
@benichu, @nicholasjhenry, @sophiedeziel, @mathieugagne I changed the navbar design just a little bit (2 rows instead of 3), please tell me what you think : 

capture d ecran 2015-12-06 a 16 05 12

**Comment by benichu** [comment]
:+1:

**Comment by benichu** [comment]
can you show us a screenshot of the responsive mode?

**Comment by benichu** [comment]
before and after :)

**Comment by mdeloupy** [comment]
On mobile view : 

capture d ecran 2015-12-06 a 16 19 40

**Comment by mdeloupy** [comment]
Mobile navbar toggled : 

capture d ecran 2015-12-06 a 16 19 45

**Comment by mdeloupy** [comment]
And the `before` view can be seen in the issue description : https://github.com/montrealrb/Montreal.rb/issues/120

**Comment by mdeloupy** [comment]
@benichu  Ready for review

**Pull request merged**
